### ISSUE TITLE
Error: No voice channel provided

### ISSUE THREAD

**Issue by Turkidev** [aiko-chan-ai/Discord-video-selfbot#1]
i got this error Error: No voice channel provided

`
import { Client } from 'discord.js-selfbot-v13';
import { DiscordStreamClient } from 'discord-stream-client';

const client = new Client();
const StreamClient = new DiscordStreamClient(client);

const token = 'token';

await client.login(token);

client.on('ready', () => {
    console.log(`Logged in as ${client.user.tag}!`);
});

// Connect to a voice channel
const voiceConnection = await StreamClient.joinVoiceChannel(
    client.channels.cache.get('voiceChannelId'),
    {
        selfDeaf: false,
        selfMute: true,
        selfVideo: false,
    },
);
// Create a stream
const streamConnection = await voiceConnection.createStream();
// Create a player
const player = StreamClient.createPlayer(
    'https://dl2.issou.best/ordr/videos/render1046454.mp4', // DIRECT VIDEO URL OR READABLE STREAM HERE
    streamConnection.udp, // UDP connection
);
// Events
player.on('finish', () => {
    console.log('Finished playing');
});
// Play video !!!
player.play();
// Stop playing
player.stop();
`

**Comment by aiko-chan-ai** [comment]
pls markdown code

**Comment by aiko-chan-ai** [comment]
check `client.channels.cache.get('voiceChannelId')`

**Comment by Turkidev** [comment]
> 

what about it?

**Comment by Turkidev** [comment]
![image](https://user-images.githubusercontent.com/114973795/232458574-57f6a71f-42c3-4c2d-9106-e2e2289f7d45.png)

**Comment by aiko-chan-ai** [comment]
> ![image](https://user-images.githubusercontent.com/114973795/232458574-57f6a71f-42c3-4c2d-9106-e2e2289f7d45.png)

you didn't put the vc in

**Comment by Turkidev** [comment]
no i did
![image](https://user-images.githubusercontent.com/114973795/232458909-68d72a02-4736-49ff-b6be-6d127288de09.png)

**Comment by Turkidev** [comment]
this is it
![image](https://user-images.githubusercontent.com/114973795/232459018-20913139-6d80-4258-8f38-f5a2441ac55f.png)

**Comment by aiko-chan-ai** [comment]
`console.log(client.channels.cache.get('voiceChannelId'))`

**Comment by Turkidev** [comment]
> `console.log(client.channels.cache.get('voiceChannelId'))`

![image](https://user-images.githubusercontent.com/114973795/232459314-2f434f3e-f8ce-4a61-8f37-a8ce340bb8ae.png)

**Comment by aiko-chan-ai** [comment]
...

**Comment by Turkidev** [comment]
#sad

**Comment by lambor590** [comment]
I have also this problem.
Even if I use `message.member.voice.channel` in the `messageCreate` event it has a value of **null**.

The thing is, I also have this problem using the main library [discord.js-selfbot-v13](https://github.com/aiko-chan-ai/discord.js-selfbot-v13).
I can get the text channels, but not the voice channels.

**Comment by aiko-chan-ai** [comment]
https://github.com/aiko-chan-ai/discord.js-selfbot-v13/issues/625

**Comment by aiko-chan-ai** [comment]
v2.13.4
