### ISSUE TITLE
seek

### ISSUE THREAD

**Issue by Zsl8** [aiko-chan-ai/Discord-video-selfbot#10]
This is not an issues but idk where to contact you

so i found a way to seek the player
in ffmpeg i could not seek it after playing the video idk why
but i tried to stop just the player and re play it from the seek moment
  
In `/Media/Player.ts`

```js
  seek(time) {
    if (!this.command)
      throw new Error("Not playing");
    
      this.stop()
      this.play({
        seek: time
      })
  }
  ```  
  and in the `play` function i added
  ```js
if(options.seek) {
        this.command.seekInput(options.seek)
}
```
  
  And it worked and the player stoped only for like 1 secound
  Also i tried to change the volume in the same way but it doesn't feels right :)
  
  And in the `pause` and `resume` functions you can do something like
  ```js
(this.client.ws as any).broadcast({
    // @ts-ignore
    op: GatewayOpCodes.STREAM_SET_PAUSED,
    d: {
        stream_key: streamKey,
        paused: isPause,
    },
});
```

Just to let people know that it's paused not some kind of lag or something

These things programers needs in your cool package so please add them if you have the time 😸

**Comment by aiko-chan-ai** [comment]
> but i tried to stop just the player and re play it from the seek moment

I tried, but it didn't work for me, so I haven't implemented yet

> And in the `pause` and `resume` functions you can do something like

<3

**Comment by aiko-chan-ai** [comment]
pause & resume updated (v1.2.1)
seek: 💀

**Comment by Zsl8** [comment]
Just try the way i did it it literally worked for me without any problem

use the stop function of the player then re run it with another stop time

**Comment by aiko-chan-ai** [comment]
I thought about it early on, but it doesn't work perfectly

**Comment by aiko-chan-ai** [comment]
> Just try the way i did it it literally worked for me without any problem
> 
> use the stop function of the player then re run it with another stop time

oke done

**Comment by aiko-chan-ai** [comment]
v1.2.2 
ex: https://github.com/aiko-chan-ai/Discord-SB-Stream
