### ISSUE TITLE
stream in group dms

### ISSUE THREAD

**Issue by MitruStefan** [aiko-chan-ai/Discord-video-selfbot#11]
is there any way to stream in group dms? ive had success in making it join vc's in group dms and play music/files, etc... but ive found no way so far to make it work with streaming

**Comment by aiko-chan-ai** [comment]
because I haven't implemented it yet

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/Discord-video-selfbot/assets/71698422/0fbfd72e-fc0e-4a9e-8a07-6f7b7db06286)
oke .-. pls wait

**Comment by aiko-chan-ai** [comment]
1.2.1
