### ISSUE TITLE
Questions: Console Spam & No Support for guild voice channel.

### ISSUE THREAD

**Issue by VanshKumar2821** [aiko-chan-ai/Discord-video-selfbot#19]
So my first question is can't this console spam be fixed? and second one is that is there no support for guild voice channel anymore?
![Latest](https://github.com/aiko-chan-ai/Discord-SB-Stream/assets/83855874/dbd6d43f-ab12-454b-855b-9b0481a38ad8)
![image](https://github.com/aiko-chan-ai/Discord-SB-Stream/assets/83855874/cc73924a-35cf-4d32-949d-2cd158d4c145)

**Comment by aiko-chan-ai** [comment]
1.4.4

**Comment by VanshKumar2821** [comment]
The Console Spam got fixed in 1.4.4 But the NO_CHANNEL issue is still there in 1.4.4. Found a fix for it from 1.2.8 => 
 if (!channel || !["DM", "GROUP_DM"].includes(channel.type) && (!channel.isVoice() || !channel.joinable))
      throw new DiscordStreamClientError("NO_CHANNEL");
      using this code in joinVoiceChannel fixes it and there's another audio issue in 1.4.4, The sound is really messed up when streaming video. To say it more specifically its like adding a bassboost filter to video

**Comment by aiko-chan-ai** [comment]
😢

**Comment by aiko-chan-ai** [comment]
I feel the sound is very normal ;-;
