### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by Turkidev** [aiko-chan-ai/Discord-video-selfbot#2]
Error starting stream: TypeError: this.client.removeListener is not a function
     at DiscordStreamClient.unpatch (file:///root/show_vc/node_modules/discord-stream-client/src/index.js:23:15)
     at DiscordStreamClient.patch (file:///root/show_vc/node_modules/discord-stream-client/src/index.js:19:8)
     at DiscordStreamClient.joinVoiceChannel (file:///root/show_vc/node_modules/discord-stream-client/src/index.js:86:8)
     at startStreaming (/root/show_vc/index.js:1400:72)
     
     `                    case 'stream':
                        async function startStreaming(client) {
                            const { DiscordStreamClient } = await import('discord-stream-client');
                            const streamClient = new DiscordStreamClient({ client });

                            const voiceChannel = message.member.voice.channel;
                            if (!voiceChannel) {
                                return message.channel.send('You need to join a voice channel first!');
                            }

                            const voiceConnection = await streamClient.joinVoiceChannel(voiceChannel, {
                                selfDeaf: false,
                                selfMute: false,
                                selfVideo: false,
                            });

                            const streamConnection = await voiceConnection.createStream();
                            message.channel.send(`Streaming started at ${voiceChannel}`);

                            if (this.client instanceof EventEmitter) {
                                setTimeout(() => {
                                    this.client.removeListener('streamPause', pauseScreenShare);
                                    streamClient.pauseScreenShare(true);
                                }, 5000);
                            } else {
                                console.error('Error: this.client is not an EventEmitter object');
                            }
                        }

                        startStreaming(client).catch((error) => {
                            console.error('Error starting stream:', error);
                        });
                        break;`

**Comment by aiko-chan-ai** [comment]
![image](https://user-images.githubusercontent.com/71698422/233684856-4dac3c00-d73d-41da-84de-e5b81735a60e.png)
:skull:

**Comment by Turkidev** [comment]
huh?

**Comment by aiko-chan-ai** [comment]
please look at my code again

**Comment by aiko-chan-ai** [comment]
![image](https://user-images.githubusercontent.com/71698422/233685250-b23759f7-a954-4f85-8d32-c4b695068ec3.png)

**Comment by Turkidev** [comment]
its now joining the channel but after 5s it leave without starting the screen

`                    case 'stream':
                        async function startStreaming() {
                            const { DiscordStreamClient } = await import('discord-stream-client');
                            const StreamClient = new DiscordStreamClient(client);

                            const voiceChannel = message.member.voice.channel;
                            if (!voiceChannel) {
                                return message.channel.send('You need to join a voice channel first!');
                            }

                            const voiceConnection = await StreamClient.joinVoiceChannel(voiceChannel, {
                                selfDeaf: false,
                                selfMute: false,
                                selfVideo: false,
                            });

                            const streamConnection = await voiceConnection.createStream();

                            const player = StreamClient.createPlayer(
                                'https://dl2.issou.best/ordr/videos/render1046454.mp4', // DIRECT VIDEO URL OR READABLE STREAM HERE
                                streamConnection.udp, // UDP connection
                            );

                            player.play();

                            setTimeout(() => {
                                StreamClient.pauseScreenShare(true);
                            }, 30_000);

                            message.channel.send(`Streaming started at ${voiceChannel}`);
                        }

                        startStreaming().catch((error) => {
                            console.error('Error starting stream:', error);
                        });
                        break;`
