### ISSUE TITLE
FFmpeg problem

### ISSUE THREAD

**Issue by Zsl8** [aiko-chan-ai/Discord-video-selfbot#20]
So when i start the screen it's fixed on black and it opens a ffmpeg termenal for no reason and when i close it the hole bot stops

![image](https://github.com/aiko-chan-ai/Discord-video-selfbot/assets/71377428/4cdcfb52-df24-4813-bab1-391b4320afd3)

**Comment by Zsl8** [comment]
So i updated my ffmpeg for the latest version and it's working fine but the termenal is still open

**Comment by Zsl8** [comment]
Ok so the termenal problem only appers when i run the bot with `pm2` it doesn't when i run it using normal power shell or cmd

**Comment by Mohammadgb0078** [comment]
I have this problem too,

@aiko-chan-ai HELP US!

**Comment by Zsl8** [comment]
> I have this problem too,
> 
> 
> 
> @aiko-chan-ai HELP US!

It's not a problem 
It's just a terminal it doesn't matter if it's shown or not

**Comment by aiko-chan-ai** [comment]
https://github.com/Unitech/pm2/issues/5041

**Comment by Mohammadgb0078** [comment]
> > I have this problem too,
> > @aiko-chan-ai HELP US!
> 
> It's not a problem It's just a terminal it doesn't matter if it's shown or not

Oh i mean i have another problem i forget to explain it

My crash and say ffmpeg not found

I installed ffmpeg on my windows and ffmpeg-static on my project
