### ISSUE TITLE
[Feature request]: A method to limit the fps "setFps"

### ISSUE THREAD

**Issue by Majoramari** [aiko-chan-ai/Discord-video-selfbot#21]
I think it is good to have a method to limit the fps like `player.setResolution("1440p");`

**Comment by aiko-chan-ai** [comment]
```js
player.play({fps: 15})
```

**Comment by Majoramari** [comment]
> ```js
> player.play({fps: 15})
> ```

Working like a charm!

```ts
<Player>.play({
    volume: 1,
    kbpsAudio: 384,
    kbpsVideo: 3072,
    fps: 15 // <-- fps here
  });
```
I'm closing this feature request because it has been implemented here: https://github.com/aiko-chan-ai/Discord-video-selfbot/commit/f9522c48445857e1f68c83590dedec70b5bc8b54 !
