### ISSUE TITLE
Pause and resume the screen

### ISSUE THREAD

**Issue by Zsl8** [aiko-chan-ai/Discord-video-selfbot#8]
Is there a way to pause and resume the screen
i tried to read the code and it tried functions like `pauseScreenShare` and the status of the screen is paused but the video keep playing

and in the future can you add a seek method is that possible?

**Comment by aiko-chan-ai** [comment]
> Is there a way to pause and resume the screen

I'm still trying, but there are some problems with buffer

> i tried to read the code and it tried functions like `pauseScreenShare` and the status of the screen is paused but the video keep playing

yeah

> and in the future can you add a seek method is that possible?

maybe...

**Comment by aiko-chan-ai** [comment]
https://github.com/aiko-chan-ai/Discord-video-selfbot/commit/8e1ff229d85737a1cf6c13f9c92e9aab830f95f7
@Zsl8 here

**Comment by aiko-chan-ai** [comment]
https://github.com/aiko-chan-ai/Discord-SB-Stream
v1.2.0
